#!/bin/sh

### ---
### Nicities
### ---

# better touchpad
synclient TapButton1=1
synclient TapButton2=3

# load fonts
xset +fp /usr/share/fonts/ohsnap
xset +fp /usr/share/fonts/symbola

# load xresources (colors etc)
xrdb ~/.Xresources

# cursor
xsetroot -cursor_name left_ptr

# background
xsetroot -solid "#`qxr background`"


### ---
### Tools
### ---

# keybindings
SXHKD_SHELL="sh" sxhkd &
SXHKD_SHELL="sh" sxhkd -c .config/sxhkd/nowm &

# focusing daemon
focusd &

# information
ibar &

# hang (run `end x` to quit)
~/bin/hang x

### ---
### deinit
### ---

killall bar
